#!/usr/bin/env ruby
require 'highline/import'

password = ask("Enter your password: ") { |q| q.echo = "*" }
rPassword = ask("Enter your password again: ") { |q| q.echo = "*" }

if password != rPassword then
  puts "Passwords didn't match"
  exit
end


Dir.glob('*').select do |f|
  if File.directory? f then
    abs = File.expand_path("./"+ f)           
    absTarZip = abs + ".tar.bz2"
    absTarZipGpg = absTarZip+".gpg"
    `tar -cyf #{absTarZip} #{abs}`
    `echo #{password} | gpg --passphrase-fd 0 -c #{absTarZip}`
    `cp  #{absTarZipGpg} ~/Sync/CV/`
    `rm #{absTarZip}`
    `rm #{absTarZipGpg}`
    puts "Backed up #{abs}"
  end  
end
puts "Goodbye"


